version: '3.9'

services:
  web:
    image: nginx:alpine
    ports:
      - '8070:80'
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - default
  php-fpm:
    build:
      dockerfile: Dockerfile
      context: .
    image: php:8-fpm
    volumes:
      - .:/var/www/html
    networks:
      - default
      - rabbitmq-net

  mysql:
    image: mysql:5.7
    container_name: royaliberia-admin-api-mysql
    working_dir: /application
    environment:
      - MYSQL_ROOT_PASSWORD=dbrootpw
      - MYSQL_DATABASE=rootsge
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpw
      - MYSQL_ALLOW_EMPTY_PASSWORD=false
      - MYSQL_RANDOM_ROOT_PASSWORD=false
    ports:
      - "9070:3306"
    networks:
      - default

  redis:
    image: redis/redis-stack-server:6.2.6-v19
    container_name: royaliberia-admin-api-redis
    ports:
      - "6370:6379"
    networks:
      - default

networks:
  rabbitmq-net:
    external: true
  default:
    driver: bridge