parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\KingsController:
        tags: ['controller.service_arguments']

    App\EventListener\ExceptionListener:
        arguments:
            - '@logger'
        tags:
            - {name: kernel.event_listener, event: kernel.exception}

    App\Service\Redis\Cache\KingsCacheService:
        arguments:
            $cache: '@kings_cache'
            $ttl: 3600